Add an alert for when querier index cache churn rate is too high.
grafana/cortex-jsonnet pull request #26
Opened 2020-04-03 19:52 UTC by cstyan

It's been a while since I did anything interesting with queries/label substitution and alerts, so let me know what we could change here to make sure this alert is useful. I based the `entries in cache < 10m` bit based on our env with the lowest value for `entries in cache / churn rate / 60s` being an average of `entry in cache for 12+ minutes`, but for other environments we have anything from 30-60 minutes.

Signed-off-by: Callum Styan <callumstyan@gmail.com>

2020-04-13 21:14 UTC, cstyan commented
bump @gouthamve

2020-04-22 08:09 UTC, gouthamve requested changes

2020-04-22 08:09 UTC, gouthamve commented on cortex-mixin/alerts.libsonnet
> +            alert: 'CortexQuerierIndexCacheChurnRate',
The metrics here are for the in-mem fifo-cache imo. We kinda don't care about the fifocache churn rate, but rather about the memcache churn rates. 

The query should be `sum without (job) (memcached_current_items) / sum without (job) (rate(memcached_items_evicted_total[5m])) < 3600`.

It shouldn't be for just index cache, but rather all caches.

2022-06-15 17:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/cortex-jsonnet?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/cortex-jsonnet?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/cortex-jsonnet?pullRequest=26) it.</sub>

2022-07-26 21:44 UTC, closed without merging