Pre-compute aggregations to optimize scaling recording rules
grafana/cortex-jsonnet pull request #284
Opened 2021-03-30 06:29 UTC by pracucci

**What this PR does**:
Based on feedback received in https://github.com/grafana/cortex-jsonnet/pull/283#issuecomment-809469271, in this PR I'm proposing to pre-compute aggregations to try to optimize the scaling recording rules.

I haven't splitted recording rules into multiple groups in this PR in order to keep the diff easier to review.

**Which issue(s) this PR fixes**:
N/A

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-03-30 10:31 UTC, tomwilkie commented on cortex-mixin/recording_rules.libsonnet
> +                quantile_over_time(0.99, cluster_namespace_deployment:container_cpu_usage_seconds_total:sum_rate[24h:5m])
Not shure the `[24h:5m]` here is the right syntax - you don't need a subquery, a plain range vector selector will do (ie just `[24h]`)

2021-03-30 10:32 UTC, tomwilkie commented on cortex-mixin/recording_rules.libsonnet
> +                quantile_over_time(0.99, cluster_namespace_deployment:container_memory_usage_bytes:sum[24h:5m])
Ditto here.

2021-03-30 20:56 UTC, beorn7 requested changes
I'd try the `[24h]` first. If that works out, great. Otherwise, we can play with the `[24h:5m]`.

2021-03-30 20:56 UTC, beorn7 commented on cortex-mixin/recording_rules.libsonnet
> +                quantile_over_time(0.99, cluster_namespace_deployment:container_cpu_usage_seconds_total:sum_rate[24h:5m])
The syntax still works. `[24h:5m]` will evaluate `cluster_namespace_deployment:container_cpu_usage_seconds_total:sum_rate` every 5m over the last 24h, thus 288 times.

`[24h]` will not evaluate anything but retrieve all the samples `cluster_namespace_deployment:container_cpu_usage_seconds_total:sum_rate` has for the last 24h. If the rule evaluation interval is 1m, that is 1440 samples.

I'm not sure what's faster, but since the latter just retrieves the time series data directly (which has to be processed anyway for the evaluation of the above), I could imagine the latter is faster, despite more data points being considered for the `quantile_over_time`.

The more important question is what the query should accomplish. I imagine the original query picked a resolution of 5m because it's barely enough to meaningfully calculate that 99th percentile, but ideally it would have had a higher resolution, but that was costly because of the subquery.

So I guess the `[24h]` form might not just be faster but also better for what we want to accomplish here.

2021-03-31 09:00 UTC, pracucci commented
Thanks @beorn7 for your detailed reply. I see your point. I removed the `:5m` step.

2021-03-31 10:22 UTC, beorn7 approved these changes

2021-03-31 10:22 UTC, beorn7 commented
Let's see how it works out.

2021-03-31 10:23 UTC, merged