feat: Allow configuration of ring members in gossip alerts
grafana/cortex-jsonnet pull request #301
Opened 2021-05-11 16:48 UTC by jdbaldry

**What this PR does**:
Allows library consumers to configure the names of jobs that are members of the gossip ring which is used by the CortexGossipMembersMismatch alert.

**Checklist**
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-05-13 08:58 UTC, simonswine commented
I have tried to fix the same problem: https://github.com/grafana/cortex-jsonnet/pull/305/files

2021-05-13 08:58 UTC, simonswine commented
I think it is probably preferable to make the components configurable

2021-05-13 12:56 UTC, simonswine requested changes

2021-05-13 12:56 UTC, simonswine commented on cortex-mixin/config.libsonnet
> +      ring_members: '(compactor|distributor|ingester|querier|ruler|store-gateway|cortex)',
I would prefer ring members being an array instead.

Also be careful with the `ingester` vs `ingester.*`

2021-05-14 12:46 UTC, jdbaldry commented on cortex-mixin/config.libsonnet
> +      ring_members: '(compactor|distributor|ingester|querier|ruler|store-gateway|cortex)',
Good catch on the `ingester` -> `ingester.*` change. I didn't mean to do that but thinking about it, I'm also not sure why it would be `ingester.*` when we relabel jobs based upon the Kubernetes name label. I probably need to change `cortex` to be `cortex$` to avoid potential naming clashes too.

2021-05-14 13:24 UTC, simonswine commented on cortex-mixin/config.libsonnet
> +      ring_members: '(compactor|distributor|ingester|querier|ruler|store-gateway|cortex)',
Guess: It might have to with some migrations. I think there were some cases were ingesters were migrated from one stateful set to another via `ingesters-temp` one.

2021-05-24 09:57 UTC, jdbaldry commented on cortex-mixin/config.libsonnet
> +      ring_members: '(compactor|distributor|ingester|querier|ruler|store-gateway|cortex)',
I've update the list to correctly match all ingester workloads and avoid matching the cortex-gateway. I've kept this as a string for now as all the other job configuration values are also strings. Is there a specific reason to prefer an array for ring_members?

2021-06-08 13:36 UTC, pracucci commented on cortex-mixin/config.libsonnet
> +      ring_members_list: ['compactor', 'distributor', 'ingester-.*', 'querier', 'ruler', 'store-gateway', 'cortex$'],
PromQL regexs are anchored, so the `cortex$` can be changed into `cortex`

2021-06-08 13:36 UTC, pracucci commented on cortex-mixin/config.libsonnet
> +      ring_members: if self.ring_members_list != null then '(%s)' % std.join('|', self.ring_members_list) else '',
I'm wondering if we could rename `ring_members_list` into `ring_members` and get rid of this `ring_members_list`. 

Keeping the 2 variables could end up to some misunderstanding: if you configure both, `ring_members_list` will be ignored. The logic in this `ring_members` could be moved to a function instead. WDYT?

2021-07-21 10:26 UTC, jdbaldry commented on cortex-mixin/config.libsonnet
> +      ring_members: ['compactor', 'distributor', 'ingester-.*', 'querier', 'ruler', 'store-gateway', 'cortex'],
Note, this presently removes the admin-api which is GEM specific.

2021-08-31 08:21 UTC, simonswine approved these changes
LGTM

2021-08-31 08:29 UTC, merged