feature: add some text boxes and descriptions to reads/writes dashboards
grafana/cortex-jsonnet pull request #324
Opened 2021-06-09 04:33 UTC by darrenjaneczek

**What this PR does**:

Focussing on the reads and writes dashboards,
added some info panels and hover-over descriptions
for some of the panels.
Some common code used by the compactor also
received additional text content.

New functions:
- addRows
- addRowsIf
...to add a list of rows to a dashboard.

The `thanosMemcachedCache` function has had some of its query text
sprawled out for easier reading and comparison with similar dashboard
queries.

**Checklist**
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-06-10 13:26 UTC, pracucci reviewed
I'm not super sure about this change because of a couple of reasons:
1. It makes some rows very verbose
2. It adds 1 panel to some (already very crowded) rows, which will make it more difficult to render nicely on not-very-large screens

2021-06-10 13:29 UTC, darrenjaneczek commented
> I'm not super sure about this change because of a couple of reasons:
> 
> 1. It makes some rows very verbose
> 2. It adds 1 panel to some (already very crowded) rows, which will make it more difficult to render nicely on not-very-large screens

Perhaps we can block these changes with a $._config setting that is defaulted to false.
However, if so, would that $.config setting also affect the text panels added to compactor.

2021-06-10 13:32 UTC, darrenjaneczek commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      editable: true,
I don't think I intended to commit this here. I will likely remove it.

2021-06-11 15:11 UTC, osg-grafana commented
Use sentence case. For more information, refer to https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings.

2021-06-11 15:12 UTC, osg-grafana requested changes
Use sentence case. For more information, refer to https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings.

2021-06-13 22:27 UTC, 09jvilla commented
@pracucci I agree that much of my original suggested text was not adding value. I have since gone back and removed much of it, leaving a "Description" text box at the top. I did make a few edits to the row names to try to be a bit more explicit. For example instead of 
"Blocks Index Cache (Store-Gateway)" its now
"Blocks Index Cache (Store-Gateway Accesses)". 
The goal here was to try to be a bit friendlier to a new operator, who might not know the relationship between the blocks index cache and store-gateway. 

To make the compactor dashboard a little easier to look at, I took the text that is already in the main branch and tucked it under the panel descriptions, eliminating the text boxes that are there today.

With these updates, we shouldn't have any rows that are wider than 3 panels, except for the 4-panel wide object storage rows (which are unchanged from what they are today in the main branch).

2021-06-14 09:02 UTC, osg-grafana submitted a review, later dismissed

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +        $.panel('Requests Per Second') +
```suggestion
        $.panel('Requests per second') +
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +          'Compaction Latency',
```suggestion
          'Compaction latency',
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +      $.row('Ingester - Blocks storage - TSDB Write Ahead Log (WAL)')
```suggestion
      $.row('Ingester - blocks storage - TSDB write ahead log (WAL)')
```
Where does this display to the user?

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +          'WAL Truncations / sec',
```suggestion
          'WAL truncations / sec',
```

2021-06-14 09:02 UTC, osg-grafana commented on cortex-mixin/dashboards/writes.libsonnet
> +          'WAL Truncations Latency (including checkpointing)',
```suggestion
          'WAL truncations latency (including checkpointing)',
```

2021-06-15 17:29 UTC, darrenjaneczek commented on cortex-mixin/dashboards/compactor.libsonnet
> +            Number of times a compactor instance triggers a compaction across all tenants its shard manage.
I am thinking "shards manage". @09jvilla ?

2021-06-15 17:42 UTC, darrenjaneczek commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      $.panel('Latency of Op: Attributes') +
Attached screenshot, @osg-grafana 
![image](https://user-images.githubusercontent.com/38694490/122099037-8e13de80-cddf-11eb-95eb-f453f14d80b8.png)

2021-06-15 17:47 UTC, darrenjaneczek commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +            name="%(cacheName)s"
In this case, it's code syntax for string formatting.

`%(VARIABLE_NAME)s`
- `%` starts the code
- `VARIABLE_NAME` in parentheses identifies the variable name
- `s` indiates that it should be a string type.

If we were doing plurals, it would look like `%(VARIABLE_NAME)ss` -- which is admittedly weird, and wouldn't work well for the `es` case, as you pointed out.

2021-06-15 17:56 UTC, darrenjaneczek commented on cortex-mixin/dashboards/reads.libsonnet
> +      $.row('Memcached – Blocks Storage – Block Index Cache (Store-gateway accesses)')  // Resembles thanosMemcachedCache
![image](https://user-images.githubusercontent.com/38694490/122100710-763d5a00-cde1-11eb-9545-47c44db9b867.png)
Added screenshot, @osg-grafana 
(The layout and some of the text in this image are out of date)

2021-06-15 18:42 UTC, 09jvilla commented on cortex-mixin/dashboards/compactor.libsonnet
> +            Number of times a compactor instance triggers a compaction across all tenants its shard manage.
Each compactor instance has a single shard. That shard defines which tenants (1 or more) that compactor must manage.

So maybe for simplicity:
"across all tenants that it manages."

2021-06-18 12:07 UTC, pracucci reviewed
Thanks for working on this and addressing my feedback. I left few comments about tiny things to fix and then we can merge.

2021-06-18 12:07 UTC, pracucci commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      $.queryPanel(
Note to reviewers: just reformatted.

2021-06-18 12:07 UTC, pracucci commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      cacheNameReadable: std.strReplace(cacheName, '-', ' '),
This is unused. I think can be removed.

2021-06-18 12:07 UTC, pracucci commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      $.latencyPanel(
Note to reviewers: just reformatted.

2021-06-18 12:07 UTC, pracucci commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      $.queryPanel(
Note to reviewers: just reformatted.

2021-06-18 12:07 UTC, pracucci commented on cortex-mixin/dashboards/dashboard-utils.libsonnet
> +      ignoring(%s) group_right() (
Note to reviewers: just reformatted.

2021-06-18 12:27 UTC, pracucci commented on cortex-mixin/dashboards/writes.libsonnet
>      .addRow(
This new row takes quite a lot of vertical space.

To make everyone happy, could we add a config option to enable/disable the dashboard description and conditionally add this row only when enabled? I'm fine to keep it enabled by default but would allow us to disable it in our infra.

2021-06-18 12:31 UTC, pracucci commented on cortex-mixin/dashboards/compactor.libsonnet
> +            Reset to `0` after the compaction run is completed for all tenants in the shard.
I tried to render these changes and doesn't look the tooltip is displayed much nicely (Grafana 8.1.0). Not a blocker for this PR, but I would suggest you to talk to grafana team.

![Screenshot 2021-06-18 at 14 30 42](https://user-images.githubusercontent.com/1701904/122561162-d03c5a80-d041-11eb-8bae-5a830ccbb5c6.png)

2021-06-21 13:22 UTC, darrenjaneczek commented on cortex-mixin/dashboards/compactor.libsonnet
> +            Reset to `0` after the compaction run is completed for all tenants in the shard.
I can fix the `0` by wrapping it in `<tt/>` instead.
I'll ask about the dark heading font.
Thanks for the heads up.

2021-06-21 13:53 UTC, pracucci commented on cortex-mixin/dashboards/compactor.libsonnet
> +            Reset to `0` after the compaction run is completed for all tenants in the shard.
Ok, thanks! Keep in mind I've commented here, but this may apply to other placesu/descriptions too (eg. the heading color applies to any description).

2021-06-22 09:55 UTC, pracucci approved these changes
LGTM, thanks!

2021-06-22 09:58 UTC, merged